name: fluid_bottom_nav_bar
description: A beautiful bottom navigation with a fluid animation. Bar color, icons and animation speed are fully customizable.
version: 1.4.0
# homepage: https://github.com/eric-taix/fluid-nav-bar
# repository: https://gith  ub.com/eric-taix/fluid-nav-bar

environment:
  sdk: ^3.10.7
  flutter: ^3.38.7

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
